import uuid
from datetime import datetime
from typing import Literal

from pydantic import BaseModel


class GatewayStatusResponse(BaseModel):
    id: str
    serial_number: str
    ts: datetime
    csq: int | None
    erf: int | None
    rst: int | None
    vgw: int | None
    # Derived from raw_payload per row (for historical health charts)
    wifi_rssi: int | None = None
    temp_c: float | None = None

    model_config = {"from_attributes": True}


class GatewayListResponse(BaseModel):
    serial_number: str
    display_name: str | None = None
    metadata: dict | None = None
    created_at: datetime
    last_seen: datetime | None
    csq: int | None
    vgw: int | None
    online: bool
    # GPS from the last telemetry (raw_payload), not a core.gateway column
    lat: float | None = None
    lng: float | None = None

    model_config = {"from_attributes": True}


class GatewayHealthResponse(BaseModel):
    """Health + presence snapshot for the gateway, derived from raw_payload.

    This is NOT history (that's /status). The two blocks are independent: if telemetry is
    missing, the health/gps fields go null but last_status_at may still be present, and
    vice versa.
    """
    serial_number: str
    # Freshness: the UI shows whether the data is from 10s ago or 8h ago
    last_telemetry_at: datetime | None = None
    last_status_at: datetime | None = None
    # Health (from the last telemetry)
    wifi_rssi: int | None = None
    uptime_sec: int | None = None
    temp_c: float | None = None
    heap_free: int | None = None
    fw: str | None = None
    lora_freq: int | None = None
    # GPS (from the last telemetry)
    gps_lat: float | None = None
    gps_lon: float | None = None
    gps_sats: int | None = None
    gps_hdop: float | None = None
    gps_alt_m: float | None = None
    # Presence (from the last status)
    state: str | None = None
    freq: int | None = None

    model_config = {"from_attributes": True}


class GatewayUpdate(BaseModel):
    display_name: str | None = None


class GatewayConfigResponse(BaseModel):
    """Active configuration decoded from the 416-byte binary struct (legacy firmware)."""
    schema_version: str = "legacy"
    config_type: str         # 'setConfig' or 'activeConfig'
    received_at: datetime
    broker: str | None
    port: int | None
    client_id: str | None
    fw_type: str | None
    topic_prefix: str | None
    interval_s: int | None
    supply_mv: int | None
    broker2: str | None

    model_config = {"from_attributes": True}


class GatewayConfigV3Response(BaseModel):
    """v3 firmware config (JSON from the gw_get ACK).

    `config` = the firmware's 5-section object (provision/runtime/lora/connect/system), with
    passwords protected (only *_pass_set is exposed). Does not expose raw_payload or config_hash.
    """
    schema_version: str = "v3"
    config: dict            # the firmware's 5 sections, raw
    fw: str | None
    net_iface: str | None
    request_id: str | None
    gateway_ts_ms: int | None
    first_seen_at: datetime
    config_updated_at: datetime
    received_at: datetime

    model_config = {"from_attributes": True}


class GatewayCommandRequest(BaseModel):
    """Outbound command to the gateway. Phase 1: ONLY {"target":"gw","action":"get"} (read-only).

    `section` is optional: a request without section = full config (response ~1KB, which does
    not fit within the firmware's MQTT payload limit over LTE — the ack comes back with
    `error:"payload_too_large", max:480`). With section, the firmware responds with just
    that part (which fits the limit). The UI decides when to request by section based on the
    gateway's `net_iface`.

    Strict validation: extra='forbid' rejects any key not listed (params/id/etc.).
    The `id` is generated by the backend — the UI does NOT send it.
    """
    target: str
    action: str
    section: Literal["provision", "runtime", "lora", "connect", "system"] | None = None

    model_config = {"extra": "forbid"}


class GatewayCommandResponse(BaseModel):
    request_id: str
    published: bool


class GatewayDeviceResponse(BaseModel):
    id: uuid.UUID
    serial_number: str
    display_name: str | None = None
    sensor_count: int
    last_seen: datetime | None
    online: bool

    model_config = {"from_attributes": True}


class GatewaySeqGap(BaseModel):
    """Gap in the gw_seq (uplink): the gateway failed to deliver N frames between after_seq
    and before_seq."""
    after_seq: int
    before_seq: int
    missing: int
    at: datetime


class GatewayUplinkGapsResponse(BaseModel):
    """Continuity of the gw_seq (the 'seq' field of the /rx wrapper) = gateway -> backend uplink.

    Distinct from node_seq (RF node->gateway, in /devices/{id}/seq-gaps). The gw_seq increments
    by 1 for every frame the gateway relays (from all its nodes combined), so it measures the
    health of the gateway's uplink as a whole. Sorted by value; large/negative jumps
    (GW reset/reboot) are discarded.
    """
    serial_number: str
    hours: int
    total_packets: int
    first_seq: int | None = None
    last_seq: int | None = None
    missing_total: int
    completeness_pct: float | None = None
    gaps: list[GatewaySeqGap]


class GwRecoveryStats(BaseModel):
    """Counters per state of the per-seq recovery mechanism (V3)."""
    pending: int = 0
    inflight: int = 0
    recovered: int = 0
    not_found: int = 0
    success_pct: float | None = None  # recovered / (recovered + not_found)


class GwRecoveryItem(BaseModel):
    """A row of recovery status for a gw_seq (Recovery tab, V3)."""
    gw_seq: int
    status: str            # pending | inflight | recovered | not_found
    reason: str | None = None
    updated_at: datetime | None = None       # COALESCE(recovered/response/inflight/first)
    recovered_at: datetime | None = None
    last_response_at: datetime | None = None


class GwRecoveryGaps(BaseModel):
    """Uplink gaps (from compute_gw_seq_gaps, reads raw) — independent of the mechanism."""
    missing_total: int = 0          # uplink frames missing within the window
    completeness_pct: float | None = None
    first_seq: int | None = None
    last_seq: int | None = None


class GwRecoveryResponse(BaseModel):
    """State of the Recovery tab (V3): per-seq stats + items + gaps."""
    serial_number: str
    stats: GwRecoveryStats
    total_items: int
    items: list[GwRecoveryItem]
    gaps: GwRecoveryGaps
